### PR TITLE
Liveness probe for GraphQL client and additional colors for monthly stats

### PR DESCRIPTION
**Pull request by fedinskiy**
1. Adds a liveness probe to restart the app if GraphQL client is stuck
2. Adds more fixed colors for monthly stats, so certain @fedinskiy will not be shown in 5 different ways on the same page :)

### CODE REVIEW

**Comment by fedinskiy** [comment]
Please do not merge, until we're sure, that the liveness probe works as expected

**Review by michalvavrik — APPROVED** [review]
I think this is very creative and a good workaround. I didn't look closer into created GraphQL client issue as I trust you there. Please confirm when you verified this with actual deployment.

**Comment by michalvavrik** [comment]
yeah, but please fix PR title.

**Comment by rsvoboda** [comment]
Do we have a way to findout how many times was the pod restarted in e.g. last 4 weeks?

**Comment by fedinskiy** [comment]
@rsvoboda if this solution works, then we will be able to see number of restarts on "workloads/pods/" section in OCP admin view.
This metric is persistent during the same deployment, so it will be cleared when we redeploy the app (I am not sure how often that happens).

**Comment by fedinskiy** [comment]
@michalvavrik @rsvoboda the restart worked as expected: https://console-openshift-console.apps.gpc.ocp-hub.prod.psi.redhat.com/k8s/ns/quarkus-qe--runtime-int/core~v1~Pod. Do you want to take a second look or this can be merged?

**Comment by rsvoboda** [comment]
No need, going to merge it now

**Pull request merged**
